### PR TITLE
Flight program interpreter feature

### PR DESCRIPTION
**Pull request by faresur**
Created FlightProframInterpreter class that works as a parser for now. Will add seperate parsers for file sections.

### CODE REVIEW

**Review by tyoma-ka — APPROVED** [review]
Found one bug, fixed it, no more bugs found

**Comment by tyoma-ka** [comment]
teraz neviem ako mergnut, tlacidlo je neaktivne 🤷‍♂️🤔

**Comment by tyoma-ka** [comment]
i mean..

image

**Comment by faresur** [comment]
Treba niekto iny, pridal som Ondreja

**Review by lexendo — APPROVED** [review]
moze byt

**Pull request merged**
